#! /bin/bash

#Chose the bookmark file
FILES=$( ls $HOME/Bookmarks )
FILE=$( echo -e "ALL\n""$FILES" | dmenu -i )

#If an option was chosen
if [[ ! -z "$FILE" ]]
then
  #Read the file
  #If is ALL, concatenate all of them
  [ $FILE = "ALL" ] && CONTENT=$( cat $HOME/Bookmarks/* ) || CONTENT=$(cat $HOME/Bookmarks/"$FILE")

  #Get the titles
  TITLES=$( echo "$CONTENT" | sed '/^http.*/d' | sed '/^$/d' | sed 's/^#//g' | sort )

  #Let the person choose the bookmark
  CHOICE=$( echo "$TITLES" | dmenu -i -l 50 )

  #Get the URL right after the title
  URL=$( echo "$CONTENT" | perl -p -e "s/#$CHOICE\n/---/" | grep '^---.*' | cut -c 4- )

  #Open it on the browser
  [[ -z "$URL" ]] || firefox "$URL"
fi
