#! /bin/bash

#   /$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$$$ /$$$$$$  /$$$$$$ 
#  /$$__  $$ /$$__  $$| $$$ | $$| $$_____/|_  $$_/ /$$__  $$
# | $$  \__/| $$  \ $$| $$$$| $$| $$        | $$  | $$  \__/
# | $$      | $$  | $$| $$ $$ $$| $$$$$     | $$  | $$ /$$$$
# | $$      | $$  | $$| $$  $$$$| $$__/     | $$  | $$|_  $$
# | $$    $$| $$  | $$| $$\  $$$| $$        | $$  | $$  \ $$
# |  $$$$$$/|  $$$$$$/| $$ \  $$| $$       /$$$$$$|  $$$$$$/
#  \______/  \______/ |__/  \__/|__/      |______/ \______/ 

TERMINAL=urxvt

PROGRAMS="aliases
bashrc
bspwm
compton
config
lemonbar
lemonbar_feed
neovim
polybar
sxhkd
xdefaults
xinitrc
xresources
zathura"


case $(echo -e "$PROGRAMS" | $DM -p "What to configure?") in

  "aliases")
    $TERMINAL -e nvim $HOME/.bash_aliases
    ;;
  "bashrc")
    $TERMINAL -e nvim $HOME/.bashrc
    ;;
  "bspwm")
    $TERMINAL -e nvim $HOME/.config/bspwm/bspwmrc
    ;;
  "compton")
    $TERMINAL -e nvim $HOME/.config/compton.conf
    ;;
  "config")
    $TERMINAL -e nvim $HOME/.scripts/config
    ;;
  "lemonbar")
    $TERMINAL -e nvim $HOME/.config/lemonbar/panel
    ;;
  "lemonbar_feed")
    $TERMINAL -e nvim $HOME/.config/lemonbar/feed
    ;;
  "neovim")
    $TERMINAL -e nvim $HOME/.config/nvim/init.vim
    ;;
  "polybar")
    $TERMINAL -e nvim $HOME/.config/polybar/config
    ;;
  "sxhkd")
    $TERMINAL -e nvim $HOME/.config/sxhkd/sxhkdrc
    ;;
  "urxvt")
    $TERMINAL -e nvim $HOME/.Xdefaults
    ;;
  "xinitrc")
    $TERMINAL -e nvim $HOME/.xinitrc
    ;;
  "xdefaults")
    $TERMINAL -e nvim $HOME/.Xdefaults
    ;;
  "xresources")
    $TERMINAL -e nvim $HOME/.Xresources
    ;;
  "zathura")
    $TERMINAL -e nvim $HOME/.config/zathura/zathurarc
    ;;

esac
