#! /bin/bash

TERMINAL=urxvt

PROGRAMS="aliases
bashrc
bspwm
compton
config
lemonbar
lemonbar_feed
nvim
polybar
sxhkd
urxvt
xinitrc
zathura"


case $(echo -e "$PROGRAMS" | dmenu -nb \#000000 -sb \#101010 -fn "$FONT" -b -i -p "Which action to take?") in

  "aliases")
    $TERMINAL -e nvim $HOME/.bash_aliases
    ;;
  "bashrc")
    $TERMINAL -e nvim $HOME/.bashrc
    ;;
  "bspwm")
    $TERMINAL -e nvim $HOME/.config/bspwm/bspwmrc
    ;;
  "compton")
    $TERMINAL -e nvim $HOME/.config/compton.conf
    ;;
  "config")
    $TERMINAL -e nvim $HOME/.scripts/config
    ;;
  "lemonbar")
    $TERMINAL -e nvim $HOME/.config/lemonbar/panel
    ;;
  "lemonbar_feed")
    $TERMINAL -e nvim $HOME/.config/lemonbar/feed
    ;;
  "nvim")
    $TERMINAL -e nvim $HOME/.config/nvim/init.vim
    ;;
  "polybar")
    $TERMINAL -e nvim $HOME/.config/polybar/config
    ;;
  "sxhkd")
    $TERMINAL -e nvim $HOME/.config/sxhkd/sxhkdrc
    ;;
  "urxvt")
    $TERMINAL -e nvim $HOME/.Xdefaults
    ;;
  "xinitrc")
    $TERMINAL -e nvim $HOME/.xinitrc
    ;;
  "zathura")
    $TERMINAL -e nvim $HOME/.config/zathura/zathurarc
    ;;

esac
