#! /bin/bash

PROMPT="Keyboard layout to use:"
OPTIONS="Us\nInternational"

CHOICE=$(echo -e "$OPTIONS" | $DM -p "$PROMPT")

case $( echo $CHOICE ) in
  "Us")
    setxkbmap us
    ;;
  "International")
    setxkbmap -layout us -variant intl
    ;;
esac
