#! /bin/bash

PROMPT="Which keyboard layout do you want to use?"
OPTIONS="Us\nInternational"

CHOICE=$(echo -e "$OPTIONS" | dmenu -i -p "$PROMPT")

case $( echo $CHOICE ) in
  "Us")
    setxkbmap us
    ;;
  "International")
    setxkbmap -layout us -variant intl
    ;;
esac
