#! /bin/bash

case $(echo -e "Power Off\nReboot\nLog Off" | $DM -p "Action to take:") in
  "Power Off")
    sh $HOME/.scripts/poweroff
    ;;
  "Reboot")
    sh $HOME/.scripts/reboot
    ;;
  "Log Off")
    sh $HOME/.scripts/logoff
    ;;
esac
