#! /bin/bash

wget -O $HOME/Downloads/discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
sudo dpkg -i $HOME/Downloads/discord.deb
sudo apt --fix-broken install
sudo dpkg -i $HOME/Downloads/discord.deb
rm $HOME/Downloads/discord.deb

