#! /bin/bash

mkdir -p $HOME/.local/share/vlc/lua/playlist
curl https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua > $HOME/.local/share/vlc/lua/playlist/youtube.lua 
