#! /bin/bash

# Make some useful folders
mkdir -p $HOME/local/bin
mkdir -p $HOME/local/src
mkdir -p $HOME/Test
mkdir -p $HOME/Pictures

# Install all the basic stuff
sudo apt-get install -y build-essential calcurse chocolate-doom cmatrix compton dmenu dtrx exfat-fuse exfat-utils feh ffmpeg firefox-esr galculator gawk groff libpulse-dev linux-headers-$(uname -r) sensors-detect make ncdu neovim ntfs-3g pulseaudio ranger rxvt-unicode-256color stow sxhkd sxiv trash-cli tty-clock vlc xorg zathura zathura-djvu zathura-pdf-poppler

# To get the video drivers working
sudo apt-get install firmware-linux-nonfree libgl1-mesa-dri libglx-mesa0 mesa-vulkan-drivers xserver-xorg-video-all
sudo dpkg --add-architecture i386 && sudo apt update
sudo apt-get install libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386

# Add these lines to /etc/apt/sources.list
sudo echo -e "\ndeb http://deb.devuan.org/merged beowulf main contrib non-free" >> "/etc/apt/sources.list"
sudo echo "deb http://deb.devuan.org/merged beowulf-security main contrib non-free" >> "/etc/apt/sources.list"

sudo apt install firmware-amd-graphics 


# install trans (translator)
#cd ~/.local/bin/
#wget git.io/trans
#chmod +x ./trans
 
# install polybar
#cd ~/Test
#wget https://github.com/polybar/polybar/releases/download/3.4.0/polybar-3.4.0.tar
#dtrx polybar-3.4.0.tar
#cd polybar
#mkdir build
#cd build
#cmake ..
#make -j$(nproc)
#sudo make install
#sudo apt-get install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2

# install youtube viewer
#cd ~/Test
#sudo apt-get install libterm-readline-gnu-perl
#git clone https://github.com/trizen/youtube-viewer.git
#cd youtube-viewer
#sudo cpan Module::Build
#perl Build.PL
#sudo ./Build installdeps
#sudo ./Build install
#cd ..
#trash youtube-viewer
